
-- 사용자 정보를 저장할 테이블 생성
create table users (
  id uuid primary key default uuid_generate_v4(), -- 사용자의 고유 ID (UUID)
  email text unique not null, -- 사용자 이메일 (중복 불가)
  password text, -- 비밀번호 (provider가 credential인 경우)
  name text, -- 사용자 이름
  image text, -- 프로필 이미지 URL
  provider text check (provider in ('credential', 'google')) not null, -- 인증 제공자
  created_at timestamp with time zone default timezone('utc'::text, now()) not null -- 생성 시간
);

-- UUID 확장 활성화
create extension if not exists "uuid-ossp";

-- 대화방 정보를 저장할 테이블 생성
create table conversations (
  id bigint generated by default as identity primary key, -- 각 대화방의 고유 ID (자동 증가)
  user_id uuid references users(id) not null, -- 대화방 소유자 (users 테이블 ID 참조)
  title text, -- 대화방 제목 (선택 사항)
  created_at timestamp with time zone default timezone('utc'::text, now()) not null -- 생성 시간
);

-- 각 대화 메시지를 저장할 테이블 생성
create table messages (
 id bigint generated by default as identity primary key, -- 각 메시지의 고유 ID (자동 증가)
 conversation_id bigint references conversations(id) not null, -- 어떤 대화방에 속하는지 (conversations 테이블 ID 참조)
 user_id uuid references users(id) not null, -- 메시지 작성자 (users 테이블 ID 참조)
 role text check (role in ('user', 'assistant', 'system')) not null, -- 메시지 역할 (사용자, AI, 시스템)
 content text not null, -- 메시지 내용
 created_at timestamp with time zone default timezone('utc'::text, now()) not null -- 생성 시간
);
