-- 기존 테이블 안전하게 삭제
DROP TABLE IF EXISTS public.messages;
DROP TABLE IF EXISTS public.conversations;
DROP TABLE IF EXISTS public.users;

-- UUID 확장 활성화 (uuid_generate_v4 함수 사용을 위해)
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 사용자 계정 테이블 생성
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  email text NOT NULL UNIQUE,
  password text NULL,
  name text NULL,
  image text NULL,
  provider text NULL,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT users_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

-- 이메일 인덱스 생성
CREATE INDEX IF NOT EXISTS users_email_idx ON public.users USING btree (email) TABLESPACE pg_default;

-- 대화 테이블 생성
CREATE TABLE public.conversations (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id uuid NOT NULL,
  title text NULL,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT conversations_pkey PRIMARY KEY (id),
  CONSTRAINT conversations_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) TABLESPACE pg_default;

-- 사용자 ID 인덱스 생성
CREATE INDEX IF NOT EXISTS conversations_user_id_idx ON public.conversations USING btree (user_id) TABLESPACE pg_default;

-- 메시지 테이블 생성
CREATE TABLE public.messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  conversation_id bigint NOT NULL,
  user_id uuid NOT NULL,
  role text NOT NULL,
  content text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT messages_pkey PRIMARY KEY (id),
  CONSTRAINT messages_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES conversations(id) ON DELETE CASCADE,
  CONSTRAINT messages_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT messages_role_check CHECK (
    (
      role = ANY (
        ARRAY['user'::text, 'assistant'::text, 'system'::text]
      )
    )
  )
) TABLESPACE pg_default;

-- 메시지 인덱스 생성
CREATE INDEX IF NOT EXISTS messages_conversation_id_idx ON public.messages USING btree (conversation_id) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS messages_user_id_idx ON public.messages USING btree (user_id) TABLESPACE pg_default;