create table conversations (
  id bigint generated by default as identity primary key, -- 각 대화방의 고유 ID(자동 증가)
  title text, -- 대화방 제목
  created_at timestamp with time zone default timezone('utc'::text, now()) not null -- 생성 시간
);

-- 각 대화 메시지를 저장할 테이블 생성
create table messages (
  id bigint generated by default as identity primary key, -- 각 대화방의 고유 ID(자동 증가)
  conversation_id bigint references conversations(id) not null, --어떤 대화방에 속하는지 (conversations 테이블 ID 참조)
  role text check (role in ('user', 'assistant', 'system')) not null, -- 메시지 역할(사용자, AI, 시스템)
  content text not null, -- 메시지 내용
  created_at timestamp with time zone default timezone('utc'::text, now()) not null -- 생성 시간
);

-- messages 테이블과 conversation_id 컬럼에 인덱스 생성 (조회 성능 향상)
create index messages_conversation_id_idx on messages (conversation_id);

